---
abstract: 'use L<Future> with L<POE>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: '0.88'
  Test::Timer: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Future
provides:
  POE::Future:
    file: lib/POE/Future.pm
    version: '0.03'
requires:
  Future: '0.05'
  POE: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.03'
